#' Test Data
#'
#' A tibble  generated from reading a typical .log file generated from a optimization job under Gaussian 16 using `readr::read_log()`. The optimization process ended up with a failure and generated long records of optimization and SCF convergence. The oscillation can be observed in the file and thus showing the advantage of this package that it can easily help calculation chemists monitor the convergence (opti or SCF) process and decide whether halt the job or not.
#' This piece of data is generated by author using Gaussian 16 rev A.03
#'
#' @format ## `TestData`
#' A tibble with 5 columns and 52,850 rows
#'
#' \describe{
#' }
"TestData"