#' Acquire Path to SCFMonitor Example data
#'
#' Makes the TestData.log, a log file generated by Gaussian 16 for testing the package, easy to access.
#' @returns A string vector showing the path to
#' @export
#' @examples
#' FormOptiSCFConvergenceRoundTibble(SCFMonitorExample())
#'
#' @name SCFMonitorExample

SCFMonitorExample <- function() {
  system.file("extdata", "TestData.log", package = "SCFMonitor")
}
